### ISSUE TITLE
Wrong package_path

### ISSUE THREAD

**Issue by Narthe** [steiza/simplepypi#6]
Hello, i try using your package but i get this error, i don't understand why os.path.join is adding slashes in the package_path since i'm running this on windows

```
>C:\Python27\python.exe C:\Python27\Scripts\simplepypi
Running on http://127.0.0.1:8000
2017-06-06 11:35:17,861 - INFO - 200 GET / (127.0.0.1) 0.00ms
2017-06-06 11:35:17,913 - WARNING - 404 GET /favicon.ico (127.0.0.1) 1.00ms
2017-06-06 11:35:19,963 - ERROR - Uncaught exception GET /packages (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='GET', uri='/packages', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Accept-Language': 'fr-FR,fr;q=0.8,en-US;q=0.6,en;q=0.4', 'Accept-Encoding': 'gzip, deflate, sdch, br', 'Host': '127.0.0.1:8000', 'Accept': 'text/html,applicat
ion/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36', 'Dnt': '1', 'Connection': 'keep-alive', 'Referer': 'http://127.0.0.1:8000/', 'Upgrade-Insecure-Requests': '1'
})
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\tornado\web.py", line 1509, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "C:\Python27\Scripts\simplepypi", line 141, in get
    contents = os.listdir(package_path)
WindowsError: [Error 3] The system cannot find the path specified: 'C:\\Python27\\Scripts\\packages/*.*'
```

**Comment by steiza** [comment]
Ah, whoops! I assume the `package` directory would be created by the user, but in retrospect that's a bit silly.

I updated the code to check if this directory exists on startup and creates it if it doesn't exist. The new version (0.1.2) is up on pypi and you should be able to update with `C:\Python27\Scripts\pip.exe install --upgrade simplepypi`.

I previously hadn't tried running `simplepypi` on Windows, but I believe it should work just fine. Let me know if you run into any other issues and thanks for reporting!

**Comment by Narthe** [comment]
Sorry i should have guessed it. Thanks anyway for the new version !
